# New and improved GNU makefile
.PHONY: world
all: world
librustyaxe := librustyaxe.so
librrprotocol := librrprotocol.so

VERSION=$(shell cat .version)
DATE=$(shell date +%Y%m%d)
INSTALLER=rrclient.win64.${DATE}.exe

include mk/json-config.mk
BUILD_DIR := ./build/${PROFILE}
include mk/compile.mk
include mk/database.mk
include mk/eeprom.mk

extra_clean += $(wildcard ${BUILD_DIR}/*.h) $(wildcard */compile_commands.json)
extra_clean += ${EEPROM_FILE} ${librustyaxe} ${librrprotocol}
extra_clean += firmware.log

BUILD_HEADERS += $(wildcard ${BUILD_DIR}/eeprom_layout.h)
BUILD_HEADERS += $(wildcard ${BUILD_DIR}/*.h)
BUILD_HEADERS += $(wildcard inc/librrprotocol/*.h)
BUILD_HEADERS += $(wildcard inc/librustyaxe/*.h)

# Generated by ./tools/pack-eeprom.pl before any library/object is compiled;
# order-only prerequisites are used because the targets are produced by the
# same pack-eeprom invocation and their timestamps must not force relinking.
EEPROM_GENERATED := ${BUILD_DIR}/build_config.h ${BUILD_DIR}/eeprom_types.h ${BUILD_DIR}/eeprom_layout.h
OBJECT_ORDER_ONLY := | ${EEPROM_GENERATED}

# Directory-stamping prerequisites ensure the build tree exists before
# pack-eeprom-derived objects are written.
${BUILD_DIR}/librustyaxe/.timestamp ${BUILD_DIR}/librrprotocol/.stamp: ${BUILD_DIR}/.stamp

# Any build/ tree object (e.g. mongoose.c -> build/$PROFILE/librustyaxe/mongoose.o)
# must wait for pack-eeprom to generate the headers in build/$PROFILE first.
${BUILD_DIR}/%.o: | ${EEPROM_GENERATED}

ifeq (${PLATFORM},posix)
LDFLAGS += -lgpiod
endif

extra_clean += ${librustyaxe} librustyaxe/irc-test
include librustyaxe/rules.mk
include librrprotocol/rules.mk
include libfwdspmgr/rules.mk

ifeq (${BUILD_RRCLIENT},true)
include rrclient/rules.mk
endif

ifeq (${BUILD_RRSERVER},true)
include rrserver/rules.mk
endif

ifeq (${BUILD_FWDSP},true)
include fwdsp/rules.mk
endif

include mk/install.mk
include mk/win64.mk
include mk/audit.mk
include mk/clean.mk
include mk/git.mk
include mk/debug.mk
include mk/resource.mk
include mk/packaging.mk

# pack-eeprom-generated files (see mk/eeprom.mk) are built in one run.
${EEPROM_FILE}: $(wildcard res/*.json)

${BUILD_DIR}/.stamp:
	mkdir -p "${BUILD_DIR}"
	touch $@

world: after-eeprom

# Build configured programs and run the maintained project test suites.
# The external librustyaxe submodule suite can be selected explicitly.
TEST_SUITES ?= selftest librustyaxe librrprotocol rrserver rrclient fwdsp www
.PHONY: test
test tests: ${bins}
	./tests/run-tests.sh ${TEST_SUITES}

after-eeprom: ${EEPROM_FILE} ${BUILD_DIR}/build_config.h
after-eeprom: ${BUILD_DIR}/.stamp ${extra_build} ${bins}

audit-log:
	./tools/rr-get-audit-log

chat-log:
	./tools/rr-get-chat-log

ptt-log:
	./tools/rr-get-ptt-log

# Native programs and the child share the codec list and fallback pipelines.
${BUILD_DIR}/rrclient/defconfig.o ${BUILD_DIR}/rrserver/defconfig.o ${BUILD_DIR}/fwdsp/defconfig.o ${BUILD_DIR}/libfwdspmgr/fwdsp-mgr.o: fwdsp/default-pipelines.h
