comm_objs += audio.framing.o		# Audio framing stuff
comm_objs += cat.o			# CAT parsers
comm_objs += cat.kpa500.o		# amplifier control (KPA-500 mode)
comm_objs += cat.yaesu.o		# Yaesu CAT protocol
comm_objs += codecneg.o
comm_objs += debug.o			# Debug stuff
comm_objs += dict.o			# dictionary object
comm_objs += io.o			# Input/Output abstraction/portability
comm_objs += io.serial.o		# Serial port stuff
comm_objs += io.socket.o		# Socket operations
comm_objs += json.o			# turn json into dicts and dicts into json
comm_objs += util.file.o		# Misc file functions
comm_objs += util.math.o		# Misc math functions
comm_objs += util.string.o		# String utility functions
