objs += audio.o			# gstreamer based audio
objs += auth.o
objs += chat.o
objs += chat.cmd.o
objs += codecneg.o
objs += config.o
objs += debug.o			# Debug stuff
objs += defconfig.o
objs += dict.o			# dictionary object
objs += gtk.o                   # Support for a GTK user interface
objs += gtk.codecpicker.o	# codec picker widget
objs += gtk.editcfg.o		# configuration tab
objs += gtk.freqentry.o		# Frequency Entry Widget
objs += gtk.pttbtn.o		# Push To Talk (PTT) button in GUI
objs += gtk.serverpick.o        # server picker
objs += gtk.syslog.o		# syslog tab
objs += gtk.winmgr.o		# window management
objs += logger.o		# Logging facilities
objs += main.o			# main loop
objs += mongoose.o		# Mongoose http/websocket/mqtt library
objs += posix.o			# support for POSIX hosts (linux or perhaps others)
objs += userlist.o
objs += ui.help.o		# help texts
objs += util.file.o		# Misc file functions
objs += util.math.o		# Misc math functions
objs += util.string.o		# String utility functions
objs += win32.o			# support to run in windows
objs += ws.o			# Websocket transport general
objs += ws.audio.o		# Audio over websocket negotiation
objs += ws.auth.o
objs += ws.chat.o
objs += ws.rigctl.o
objs += ws.tx-audio.o
