fw_objs += amp.o			# Amplifier management
fw_objs += atu.o			# Antenna Tuner
fw_objs += au.o			# Audio channel stuff
fw_objs += au.recording.o		# Support for recording audio to files
fw_objs += auth.o			# User management
fw_objs += backend.o		# Support for multiple backends by setting up pointer into appropriate one
fw_objs += backend.dummy.o		# Dummy backend (not implemented yet - use hamlib + rigctld in dummy rig mode!)
fw_objs += backend.hamlib.o	# Support for using hamlib to control legacy rigs
fw_objs += backend.internal.o	# Internal (real hardware) backend
fw_objs += channels.o		# Channel Memories
fw_objs += console.o		# Console support
fw_objs += database.o		# sqlite3 database stuff
fw_objs += dds.o		# API for Direct Digital Synthesizers
fw_objs += dds.ad9833.o		# AD9833 DDS
fw_objs += dds.ad9959_stm32.o	# STM32 (AT command) ad9851 DDS
fw_objs += dds.si5351.o		# Si5351 synthesizer
fw_objs += defcfg.o		# Default configuration
fw_objs += eeprom.o		# "EEPROM" configuration storage
fw_objs += faults.o		# Fault management/alerting
fw_objs += filters.o		# Control of input/output filters
fw_objs += fwdsp-mgr.o		# fwdsp manager
fw_objs += gnuradio.o		# Support for GNU Radio (NYI)
fw_objs += gpio.o		# GPIO controls
fw_objs += gui.o		# Support for a local user-interface
fw_objs += gui.fb.o		# Generic LCD (framebuffer) interface
fw_objs += gui.nextion.o	# Nextion HMI display interface
fw_objs += help.o		# support for help menus from filesystem, if available
fw_objs += http.o		# HTTP server
fw_objs += http.api.o		# HTTP REST API
fw_objs += http.bans.o		# Support banning nuisance user-agents
fw_objs += i2c.o		# i2c abstraction
fw_objs += i2c.linux.o
fw_objs += i2c.mux.o		# i2c multiplexor support
fw_objs += main.o			# main loop
comm_objs += mongoose.o		# Mongoose http/websocket/mqtt library
#fw_objs += mqtt.o			# Support for MQTT via mongoose
fw_objs += network.o		# Network control
fw_objs += power.o			# Power monitoring and management
fw_objs += protection.o		# Protection features
fw_objs += ptt.o			# Push To Talk controls (GPIO, CAT, etc)
fw_objs += radioberry.o		# Radioberry device support
fw_objs += thermal.o		# Thermal management
fw_objs += timer.o			# Timers support
fw_objs += usb.o			# Support for USB control (stm32)
fw_objs += util.vna.o		# Vector Network Analyzer
fw_objs += unwind.o		# support for libunwind for stack tracing
fw_objs += vfo.o			# VFO control/management
fw_objs += waterfall.o		# Support for rendering waterfalls
fw_objs += webcam.o		# Webcam (v4l2) streaming to a canvas
fw_objs += ws.o			# Websocket transport general
fw_objs += ws.audio.o		# Audio (raw / OPUS) over websockets
fw_objs += ws.bcast.o		# Broadcasts over websocket (chat, rig status, etc)
fw_objs += ws.chat.o		# Websocket Chat (talk)
fw_objs += ws.rigctl.o		# Websocket Rig Control (CAT)
