rrserver_objs += rrserver/amp.o			# Amplifier management
rrserver_objs += rrserver/atu.o			# Antenna Tuner
rrserver_objs += rrserver/au.o			# Audio channel stuff
rrserver_objs += rrserver/au.recording.o		# Support for recording audio to files
rrserver_objs += rrserver/auth.o			# User management
rrserver_objs += rrserver/backend.o		# Support for multiple backends by setting up pointer into appropriate one
rrserver_objs += rrserver/backend.dummy.o		# Dummy backend (not implemented yet - use hamlib + rigctld in dummy rig mode!)
rrserver_objs += rrserver/backend.hamlib.o	# Support for using hamlib to control legacy rigs
rrserver_objs += rrserver/backend.internal.o	# Internal (real hardware) backend
rrserver_objs += rrserver/channels.o		# Channel Memories
rrserver_objs += rrserver/console.o		# Console support
rrserver_objs += rrserver/database.o		# sqlite3 database stuff
rrserver_objs += rrserver/dds.o		# API for Direct Digital Synthesizers
rrserver_objs += rrserver/dds.ad9833.o		# AD9833 DDS
rrserver_objs += rrserver/dds.ad9959_stm32.o	# STM32 (AT command) ad9851 DDS
rrserver_objs += rrserver/dds.si5351.o		# Si5351 synthesizer
rrserver_objs += rrserver/defconfig.o		# Default configuration
rrserver_objs += rrserver/eeprom.o		# "EEPROM" configuration storage
rrserver_objs += rrserver/faults.o		# Fault management/alerting
rrserver_objs += rrserver/filters.o		# Control of input/output filters
rrserver_objs += rrserver/fwdsp-mgr.o		# fwdsp manager
rrserver_objs += rrserver/gnuradio.o		# Support for GNU Radio (NYI)
rrserver_objs += rrserver/gpio.o		# GPIO controls
rrserver_objs += rrserver/gui.o		# Support for a local user-interface
rrserver_objs += rrserver/gui.fb.o		# Generic LCD (framebuffer) interface
rrserver_objs += rrserver/gui.nextion.o	# Nextion HMI display interface
rrserver_objs += rrserver/help.o		# support for help menus from filesystem, if available
rrserver_objs += rrserver/http.o		# HTTP server
rrserver_objs += rrserver/http.api.o		# HTTP REST API
rrserver_objs += rrserver/http.bans.o		# Support banning nuisance user-agents
rrserver_objs += rrserver/i2c.o		# i2c abstraction
rrserver_objs += rrserver/i2c.linux.o
rrserver_objs += rrserver/i2c.mux.o		# i2c multiplexor support
rrserver_objs += rrserver/main.o			# main loop
#rrserver_objs += rrserver/mqtt.o			# Support for MQTT via mongoose
rrserver_objs += rrserver/network.o		# Network control
rrserver_objs += rrserver/protection.o		# Protection features
rrserver_objs += rrserver/ptt.o			# Push To Talk controls (GPIO, CAT, etc)
rrserver_objs += rrserver/radioberry.o		# Radioberry device support
rrserver_objs += rrserver/thermal.o		# Thermal management
rrserver_objs += rrserver/timer.o			# Timers support
rrserver_objs += rrserver/usb.o			# Support for USB control (stm32)
rrserver_objs += rrserver/util.vna.o		# Vector Network Analyzer
rrserver_objs += rrserver/unwind.o		# support for libunwind for stack tracing
rrserver_objs += rrserver/vfo.o			# VFO control/management
rrserver_objs += rrserver/waterfall.o		# Support for rendering waterfalls
rrserver_objs += rrserver/webcam.o		# Webcam (v4l2) streaming to a canvas
rrserver_objs += rrserver/ws.o			# Websocket transport general
rrserver_objs += rrserver/ws.audio.o		# Audio (raw / OPUS) over websockets
rrserver_objs += rrserver/ws.bcast.o		# Broadcasts over websocket (chat, rig status, etc)
rrserver_objs += rrserver/ws.chat.o		# Websocket Chat (talk)
rrserver_objs += rrserver/ws.rigctl.o		# Websocket Rig Control (CAT)
