//      This is part of rustyrig-fw. https://github.com/pripyatautomations/rustyrig-fw
//
// Do not pay money for this, except donations to the project, if you wish to.
// The software is not for sale. It is freely available, always.
//
// Licensed under MIT license, if built without mongoose or GPL if built with.
/*
 * This file is autogenerated by buildconf, please do not edit it directly.
 * Please edit config/radio.config.json then re-run './buildconf.pl radio' to make changes.
 */
#if !defined(_config_h)
#define _config_h

#define HARDWARE "sb50"
#define	USE_EEPROM true
#define EEPROM_TYPE_MMAP true
#undef EEPROM_TYPE_I2C
#define EEPROM_MMAP_ADDR 0x0000
#define	NOISY_EEPROM true
#define RR_MAX_AMPS		2
#define RR_MAX_ATUS		4
#define RR_MAX_FILTERS		4
// XXX: Move to cfg:rig*.tot-time and cfg:global.tot-time

#define RF_TALK_TIMEOUT		300
#define MASTERDB_PATH "./db/master.db"
#define MASTERDB_TEMPLATE "./sql/sqlite.master.sql"
// This one breaks build but should be sorted out soon.
//#define CAT_KPA500 true
#define CAT_YAESU true
#define FEATURE_GSTREAMER
#define FEATURE_SQLITE

// XXX: This needs moved to config/loadable modules
#define BACKEND_HAMLIB
#define BACKEND_HAMLIB_DEBUG	RIG_DEBUG_WARN
#define BACKEND_HAMLIB_MODEL	2
#define BACKEND_HAMLIB_BAUD	38400
#define BACKEND_HAMLIB_PORT	"localhost:4532"


//#define USE_PROFILING true
#define	USE_MONGOOSE
#define FEATURE_MQTT
#define FEATURE_HTTP

#define HTTP_USE_TLS 1
#define HTTP_TLS_KEY "./config/key.pem"
#define HTTP_TLS_CERT "./config/cert.pem"
#define HTTP_AUTHDB_PATH	"./config/http.users"
#define EEPROM_SIZE 1048576
#define MAX_BANDS 14
#define HOST_EEPROM_FILE "build/release/eeprom.bin"
#define HOST_CAT_PIPE "cat.fifo"
#define HOST_POSIX
#define HOST_LINUX	// This should not be here, but i2c depends on it for now
#endif
./librrprotocol/auth.h
./librrprotocol/http.c
./librrprotocol/ws.audio.c
./librrprotocol/ws.auth.c
./librrprotocol/ws.c
./librrprotocol/ws.chat.c
./librrprotocol/ws.chat.cli.c
./librrprotocol/ws.cli.c
./librrprotocol/ws.file-xfer.c
./librrprotocol/ws.rigctl.c
./librrprotocol/ws.rigctl.cli.c
./librustyaxe/cat.c
./librustyaxe/config.c
./librustyaxe/eeprom.c
./librustyaxe/kvstore.c
./librustyaxe/subproc.c
./modsrc/mod.ui.gtk3/gtk.winmgr.c
./rrgtk/chat.c
./rrgtk/disabled/audio.c
./rrserver/disabled/dds.ad9959_stm32.c
./rrserver/disabled/fwdsp-mgr.c
./rrserver/main.c
./rrserver/ptt.c
