/*
 * This file is autogenerated by buildconf, please do not edit it directly.
 * Please edit config/radio.config.json then re-run './buildconf.pl radio' to make changes.
 */
#if     !defined(_eeprom_layout_h)
#define _eeprom_layout_h
#include "eeprom_types.h"
/* This is only useed in eeprom.c */
#if   defined(EEPROM_C)
static struct eeprom_layout eeprom_layout[] = {
   { .key = "backend/active", .type = EE_STR, .offset = 358, .size = 10 },
   { .key = "debug/loglevel", .type = EE_STR, .offset = 0, .size = 6 },
   { .key = "debug/show_ts", .type = EE_BOOL, .offset = 248, .size = 1 },
   { .key = "dev/hwversion", .type = EE_INT, .offset = 11, .size = 4 },
   { .key = "dev/serial", .type = EE_INT, .offset = 7, .size = 4 },
   { .key = "eeprom/version", .type = EE_INT, .offset = 15, .size = 4 },
   { .key = "features/auto_block_ptt", .type = EE_BOOL, .offset = 19, .size = 1 },
   { .key = "fw/major", .type = EE_INT, .offset = 23, .size = 4 },
   { .key = "fw/minor", .type = EE_INT, .offset = 27, .size = 4 },
   { .key = "net/bind", .type = EE_STR, .offset = 39, .size = 32 },
   { .key = "net/dns1", .type = EE_IP4, .offset = 71, .size = 4 },
   { .key = "net/dns2", .type = EE_IP4, .offset = 75, .size = 4 },
   { .key = "net/gw", .type = EE_IP4, .offset = 79, .size = 4 },
   { .key = "net/http/404_path", .type = EE_STR, .offset = 249, .size = 101 },
   { .key = "net/http/bind", .type = EE_IP4, .offset = 218, .size = 4 },
   { .key = "net/http/enabled", .type = EE_BOOL, .offset = 230, .size = 1 },
   { .key = "net/http/port", .type = EE_INT, .offset = 222, .size = 4 },
   { .key = "net/http/tls_port", .type = EE_INT, .offset = 350, .size = 4 },
   { .key = "net/http/www_root", .type = EE_STR, .offset = 249, .size = 101 },
   { .key = "net/interface", .type = EE_STR, .offset = 83, .size = 6 },
   { .key = "net/ip", .type = EE_IP4, .offset = 89, .size = 4 },
   { .key = "net/mask", .type = EE_IP4, .offset = 93, .size = 4 },
   { .key = "net/mqtt/bind", .type = EE_IP4, .offset = 231, .size = 4 },
   { .key = "net/mqtt/enabled", .type = EE_BOOL, .offset = 247, .size = 1 },
   { .key = "net/mqtt/port", .type = EE_INT, .offset = 239, .size = 4 },
   { .key = "net/mtu", .type = EE_INT, .offset = 97, .size = 4 },
   { .key = "net/vlan", .type = EE_INT, .offset = 101, .size = 4 },
   { .key = "owner/call", .type = EE_CALL, .offset = 105, .size = 16 },
   { .key = "owner/privs", .type = EE_CLASS, .offset = 121, .size = 3 },
   { .key = "pin/master", .type = EE_STR, .offset = 123, .size = 8 },
   { .key = "pin/reset", .type = EE_STR, .offset = 131, .size = 8 },
   { .key = "pin/show", .type = EE_BOOL, .offset = 139, .size = 1 },
   { .key = "station/call", .type = EE_CALL, .offset = 142, .size = 16 },
   { .key = "station/grid", .type = EE_GRID, .offset = 158, .size = 8 },
   { .key = "therm/encl_alarm", .type = EE_INT, .offset = 166, .size = 4 },
   { .key = "therm/encl_max", .type = EE_INT, .offset = 170, .size = 4 },
   { .key = "therm/encl_target", .type = EE_INT, .offset = 174, .size = 4 },
   { .key = "therm/final_alarm", .type = EE_INT, .offset = 178, .size = 4 },
   { .key = "therm/final_max", .type = EE_INT, .offset = 182, .size = 4 },
   { .key = "therm/final_target", .type = EE_INT, .offset = 186, .size = 4 },
   { .key = "therm/inlet_alarm", .type = EE_INT, .offset = 190, .size = 4 },
   { .key = "therm/inlet_max", .type = EE_INT, .offset = 194, .size = 4 },
   { .key = "therm/inlet_target", .type = EE_INT, .offset = 198, .size = 4 },
   { .key = "therm/lpf_alarm", .type = EE_INT, .offset = 202, .size = 4 },
   { .key = "therm/lpf_max", .type = EE_INT, .offset = 206, .size = 4 },
   { .key = "therm/lpf_target", .type = EE_INT, .offset = 210, .size = 4 },
};
#endif /* defined(EEPROM_C) */
#endif /* defined(__eprom_layout_h) */
