//      This is part of rustyrig-fw. https://github.com/pripyatautomations/rustyrig-fw
//
// Do not pay money for this, except donations to the project, if you wish to.
// The software is not for sale. It is freely available, always.
//
// Licensed under MIT license, if built without mongoose or GPL if built with.
/*
 * This file is autogenerated by buildconf, please do not edit it directly.
 * Please edit config/radio.config.json then re-run './buildconf.pl radio' to make changes.
 */
#if !defined(_eeprom_types_h)
#define _eeprom_types_h

enum ee_data_type {                      /* Type of the data */
   EE_BOOL,			/* Boolean (true/false) */
   EE_CALL,			/* Ham callsign */
   EE_CHAN_GROUPS,			/* Chan Groups */
   EE_CHAN_HEADER,			/* Channel Mem Header */
   EE_CHAN_SLOT,			/* Channel memory */
   EE_CLASS,			/* License Class */
   EE_FLOAT,			/* Decimal (floating point) numbers */
   EE_FREQ,			/* A frequency */
   EE_GRID,			/* Maidenhead gridsquare */
   EE_INT,			/* Whole numbers */
   EE_IP4,			/* IPv4 address */
   EE_IP6,			/* IPv6 address */
   EE_MODE,			/* Operating mode (modulation) */
   EE_STR,			/* Text string, fixed length NULL pad */
};
typedef enum ee_data_type ee_data_type;

#endif /* !defined(_eeprom_types_h) */
