/*
 * This file is autogenerated by buildconf, please do not edit it directly.
 * Please edit config/radio.config.json then re-run './buildconf.pl radio' to make changes.
 */
#if !defined(_config_h)
#define _config_h
#define FEATURE_GSTREAMER
#define FEATURE_HTTP
#define USE_PROFILING true
#define LOG_FILE "rrclient.log"
#endif
