#!/usr/bin/env bash
# Format tracked, owned C sources, including frontend and test subdirectories.
set -euo pipefail
root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"
for formatter in indent uncrustify; do
   if ! command -v "$formatter" >/dev/null; then
      printf 'Required formatter not found: %s\n' "$formatter" >&2
      exit 1
   fi
done
# Ignore personal indent profiles; use the repository's explicit options.
mapfile -t indent_options < "$root/.indent.pro"
workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT
mapfile -d '' files < <(git ls-files -z -- '*.c' '*.h')
for component in librustyaxe librrprotocol callsign-lookup; do
   while IFS= read -r -d '' file; do
      files+=("$component/$file")
   done < <(git -C "$component" ls-files -z -- '*.c' '*.h')
done
for file in "${files[@]}"; do
   case "$file" in
      ext/*|*/ext/*|www/*|debian/*|build/*|snippets/*) continue ;;
      librrprotocol/wire-registry.h) continue ;; # Regenerated from wire-schema.json.
      inc/eeprom_layout.h|inc/eeprom_types.h) continue ;; # Generated by buildconf.
   esac
   [[ -f "$file" ]] || continue
   indent -npro "${indent_options[@]}" "$file" -o "$workdir/indent.c"
   uncrustify -q -c "$root/.uncrustify.cfg" -l C -f "$workdir/indent.c" -o "$workdir/formatted.c"
   if ! cmp -s "$file" "$workdir/formatted.c"; then
      cat "$workdir/formatted.c" > "$file"
   fi
done
